[workspace]
members = [
    "rust",
]

[workspace.metadata.raze]
genmode = "Remote"
workspace_path = "//cargo"
targets = [
    "aarch64-apple-darwin",
]
experimental_api = true
default_gen_buildrs = true
render_package_aliases = false